ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('a/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('accounts2/',include('users.urls', namespace='users')),
    path('accounts/',include('allauth.urls')),
    path('admin/',include('admindashboard.urls', namespace='a')),
    path('profile/',include('profiles.urls', namespace='profiles')),
    path('orders/', include('orders.urls', namespace='orders')),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
	path('checkout/', views.Checkout.as_view(), name = 'checkout'),
	path('confirm/<int:pk>/', views.ConfirmOrder.as_view(), name = 'confirm-order'),
	path('handlerequest/', views.handlerequest, name= 'handlerequest'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
	path('', views.ProductsList.as_view(), name = 'list_products'),
	path('all_product/', views.All_ProductsList.as_view(), name = 'all_products'),
	path('product_detail/<int:pk>/', views.ProductDetail.as_view(), name = 'product_detail'),
	path('cart/', views.CartList.as_view(), name='cart'),
	path('contact/', views.ContactFormPage.as_view(), name='contact-us'),
	path('terms_condition/', views.Terms_Condition, name = 'terms_condition'),
	path('privacy_policy/', views.Privacy_Policy, name = 'privacy_policy'),
	path('about_us/', views.about_us, name = 'about_us'),
	path('shipping_policy/', views.return_refund, name = 'return_refund'),
	path('how_to_buy/', views.how_to_buy, name = 'how_to_buy'),
	path('exchange/', views.exchange, name = 'exchange'),
	path('size_chart/', views.size, name = 'size'),
	path('add-to-cart/', views.AddToCart.as_view(), name = 'add_to_cart'),
	path('increment/<int:pk>/', views.IncrementCart.as_view(), name = 'increment'),
	path('decrement/<int:pk>/', views.DecrementCart.as_view(), name = 'decrement'),
	path('remove-from-cart/<int:pk>/', views.DeleteFromCart.as_view(), name='remove_from_cart'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
]

products/models.py
from django.db import models
from django.shortcuts import reverse
from django.conf import settings
from django.db.models import Sum
from multiselectfield import MultiSelectField
from ecommerce.storage_backends import MediaStorage


# Create your models here.
user = settings.AUTH_USER_MODEL
LABEL_CHOICES = (
    ('N', 'New Arrivals (Show on Top)'),
)

SIZE_CHOICES = (
    ('XS', 'XS'),
    ('S', 'S'),
    ('M', 'M'),
    ('L', 'L'),
    ('XL', 'XL'),
    ('34', '34'),
    ('35', '35'),
    ('36', '36'),
    ('37', '37'),
    ('38', '38'),
    ('39', '39'),
    ('40', '40'),
    ('41', '41'),
    ('42', '42'),
    ('43', '43'),
)

class Color(models.Model):
    colorcode = models.CharField(max_length=50)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Item(models.Model):
    title = models.CharField(max_length=100)
    image = models.FileField(storage=MediaStorage(), upload_to='item_images')
    image_1 = models.FileField(storage=MediaStorage(), upload_to='item_images', blank=True)
    image_2 = models.FileField(storage=MediaStorage(), upload_to='item_images', blank=True)
    image_3 = models.FileField(storage=MediaStorage(), upload_to='item_images', blank=True)
    image_4 = models.FileField(storage=MediaStorage(), upload_to='item_images', blank=True)
    is_in_stock = models.BooleanField(default=True)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, blank=True)
    colors = models.ManyToManyField(Color, blank=True)
    sizes = MultiSelectField(choices=SIZE_CHOICES, max_length=100, blank=True)
    stretchability = models.CharField(max_length=1000, blank=True, null=True)
    material = models.CharField(max_length=1000, blank=True, null=True)
    color = models.CharField(max_length=1000, blank=True, null=True)
    disclaimer = models.TextField(blank=True, null=True)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("a:item-list")
    
    def get_discount_percentage(self):
        return int(((self.price - self.discount_price)/self.price)*100)


class Cart(models.Model):
    user = models.OneToOneField(user, on_delete=models.CASCADE, related_name='cart')
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total_price(self):
        total = 0
        for item in self.cartitem_set.all():
            total += item.get_final_price()
        return total

    def get_items_count(self):
        return self.cartitem_set.all().aggregate(Sum('quantity'))['quantity__sum']


class Cartitem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    size = models.CharField(choices=SIZE_CHOICES, max_length=100, blank=True)
    color = models.CharField(max_length=100, blank=True)
    quantity = models.IntegerField(default=1)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.quantity} of {self.item.title} for {self.cart.user.username}"

    def get_item_total_price(self):
        return self.item.price * self.quantity

    def get_discount_total_price(self):
        return self.item.discount_price * self.quantity

    def get_item_final_price(self):
        if self.item.discount_price:
            return self.item.discount_price * self.quantity
        else:
            return self.item.price * self.quantity

    def get_item_final_price_single(self):
        if self.item.discount_price:
            return self.item.discount_price
        else:
            return self.item.price

    def get_amount_saved(self):
        return self.get_item_total_price() - self.get_discount_total_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_discount_total_price()
        return self.get_item_total_price()
    
    def increment(self):
        self.quantity = self.quantity + 1

    def decrement(self):
        self.quantity = self.quantity - 1

products/views.py
from django.shortcuts import render
from . models import Item, Category, Cart, Cartitem
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.views.generic import View
from ecommerce.mixins import LoginRequiredMixin
from admindashboard.forms import ContactForm
from django.core.mail import EmailMessage
from django.conf import settings
import requests
import json
from django.urls import reverse

# Create your views here.


class ProductsList(ListView):
    template_name = 'home.html'
    model = Item
    paginate_by = 8
    context_object_name = 'products'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_superuser:
            return redirect('a:dashboard')
        else:
            return super().dispatch(request, *args, **kwargs)


    def get_queryset(self):
        queryset = super(ProductsList, self).get_queryset()
        q1 = queryset.filter(label='N')  # 
        return q1

    def get_context_data(self, **kwargs):
        context = super(ProductsList, self).get_context_data(**kwargs)
        context['p1'] = Category.objects.get(name="Tops & Blouses")
        context['p2'] = Category.objects.get(name="Dresses")
        context['p3'] = Category.objects.get(name="Jumpsuits")
        context['p4'] = Category.objects.get(name="Co ord's")
        context['p5'] = Category.objects.get(name="Bottoms")
        context['p6'] = Category.objects.get(name="Winter")
        return context



class All_ProductsList(ListView):
    template_name = 'all_product.html'
    model = Item
    paginate_by = 20
    context_object_name = 'products'
    title = 'All'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_superuser:
            return redirect('a:dashboard')
        else:
            return super().dispatch(request, *args, **kwargs)


    def get_queryset(self):
        queryset = super(All_ProductsList, self).get_queryset()
        c = self.request.GET.get('c',None)
        if c is not None:
            queryset = queryset.filter(category__pk=c)
            self.title = Category.objects.get(pk=c).name
        name = self.request.GET.get('name',None)
        if name is not None:
            queryset1 = queryset.filter(title__icontains=name)
            queryset2 = queryset.filter(category__name__icontains=name)
            queryset4 = queryset.filter(description__icontains=name)
            queryset = (queryset1 | queryset2 | queryset4).distinct()
            self.title = "Results for '"+ name +"'"
        label = self.request.GET.get('l',None)
        if label is not None:
            queryset = queryset.filter(label=label)
            self.title = 'New Arrivals'
        n = self.request.GET.get('n',None)
        if n is not None:
            if n == 'C':
                queryset = super(All_ProductsList, self).get_queryset()
                categories = ['Tops & Blouses','Dresses', 'Jumpsuits', "Co ord's", 'Bottoms', 'Winter']
                self.title = 'All Clothing'
                queryset = queryset.filter(category__name__in = categories)
            if n == 'A':
                queryset = super(All_ProductsList, self).get_queryset()
                categories = ['Footwear','Bags', 'Jewellery']
                self.title = 'All Accessories'
                queryset = queryset.filter(category__name__in = categories)
        queryset = queryset.order_by('title')
        s = self.request.GET.get('s',None)
        if s is not None:
            if s == 'atoz':
                queryset = queryset.order_by('title')
            if s == 'ztoa':
                queryset = queryset.order_by('-title')
            if s == 'p1':
                queryset = queryset.order_by('price')
            if s == 'p2':
                queryset = queryset.order_by('-price')

        return queryset

    def get_context_data(self, **kwargs):
        context = super(All_ProductsList, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['title'] = self.title
        return context





class CartList(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user_cart, _ = Cart.objects.get_or_create(user=request.user)
        data = {
            'cart_items':user_cart.cartitem_set.all(),
            'total_price':user_cart.get_total_price()
        }
        return render(request, 'order_summary.html', context=data)



class ProductDetail(View):
    def get(self, request, pk, *args, **kwargs):
        product = get_object_or_404(Item, pk=pk)
        
        return render(request, 'product_detail.html', {'product': product})

class AddToCart(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        item = Item.objects.get(pk=(request.POST.get('pk')))
        if not item.is_in_stock:
            messages.error(request, 'Item Out of stock')
            return redirect('products:product_detail', pk=item.pk)
        size = request.POST.get('size',None)
        color = request.POST.get('color',None)
        quantity = int(request.POST.get('quantity','1'))
        user_cart, _ = Cart.objects.get_or_create(user=request.user)
        if size is not None:
            if color is not None:
                cart_item = user_cart.cartitem_set.all().filter(item=item, size=size, color=color)
            else:
                cart_item = user_cart.cartitem_set.all().filter(item=item, size=size)
        else:
            if color is not None:
                cart_item = user_cart.cartitem_set.all().filter(item=item, color=color)
            else:
                cart_item = user_cart.cartitem_set.all().filter(item=item)


        if cart_item.exists():
            cart_item = cart_item.first()
            for i in range(quantity):
                cart_item.increment()
            cart_item.save()
        else:
            if size is not None:
                if color is not None:
                    cart_item = Cartitem.objects.create(item=item, size=size ,cart=user_cart, color=color, quantity=quantity)
                else:
                    cart_item = Cartitem.objects.create(item=item, size=size ,cart=user_cart, quantity=quantity)
            else:
                if color is not None:
                    cart_item = Cartitem.objects.create(item=item, cart=user_cart, color=color, quantity=quantity)
                else:
                    cart_item = Cartitem.objects.create(item=item ,cart=user_cart, quantity=quantity)

        messages.info(request, 'Item is added to your cart')
        return redirect('products:cart')

class IncrementCart(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        cart_item = Cartitem.objects.get(pk=pk)
        if not cart_item.item.is_in_stock:
            cart_item.delete()
            messages.error(request, 'Item Out of stock')
            return redirect('products:cart')
        
        cart_item.increment()
        cart_item.save()
        messages.info(request, 'Item has been added to your cart')
        return redirect('products:cart')

class DecrementCart(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        cart_item = Cartitem.objects.get(pk=pk)
        if not cart_item.item.is_in_stock:
            cart_item.delete()
            messages.error(request, 'Item Out of stock')
            return redirect('products:cart')
        cart_item.decrement()
        cart_item.save()
        if cart_item.quantity == 0:
            cart_item.delete()
        messages.info(request, 'Item has been removed from your cart')
        return redirect('products:cart')


class DeleteFromCart(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        cart_item = Cartitem.objects.get(pk=pk)
        cart_item.delete()
        messages.info(request, 'Item has been removed from your cart')
        return redirect('products:cart')

class ContactFormPage(View):
    def get(self, request, *args, **kwargs):
        context = {
            'form':ContactForm,
        }
        return render(request, 'contact_us.html', context)
    
    def post(self, request, *args, **kwargs):
        form = ContactForm(request.POST, request.FILES)
        if form.is_valid():
            c = form.save()
        context = {
            'form':form
        }
        return render(request, 'contact_us.html', context)


def Terms_Condition(request):
    return render(request, 'terms_condition.html')


def Privacy_Policy(request):
    return render(request, 'privacy_policy.html' )

def about_us(request):
    return render(request, 'about_us.html')

def return_refund(request):
    return render(request, 'return_refund.html')

def exchange(request):
    return render(request, 'exchange.html')

def size(request):
    return render(request, 'size.html')

def how_to_buy(request):
    return render(request, 'how_to_buy.html')

products/templates/how_to_buy.html
{% extends "base.html" %}

{% block content %}
<div class='container mt-5 mb-2'>
	<div class='how'>
		<div class='how1'>
			<h3 style="text-align: center;"><b>HOW TO BUY</b></h3>
			<p class='how2'>Use our navigation menu to narrow down your search by Tops & Blouses, Dresses, CO-ORDS, Jumpsuits, Bottoms,Accessories. Add your favourite products to cart, check out by providing relevant address with the choice of multiple payment methods. You will be receiving order status on your registered mail I'd or mobile number.</p>
			<p class='how2'>Now, We are providing option of placing an order on Whatsapp, Instagram and Facebook. All you have to do is just drop a message.</p>
		</div>
	</div>
</div>
{% endblock content %}

products/templates/order_summary.html
{% extends "base.html" %}
{% block content %}
<div class='row justify-content-center mt-4 mx-3'>
	<div class='col-lg-10 col-md-12 col-sm-12'>
		<div class="container z-depth-1 p-3 my-5">

			<section>

				<!-- Shopping Cart table -->
				<div class="table-responsive">
					<h1 align="center">Your Cart</h1>

				<table class="table product-table table-cart-v-1">
					<!-- Table head -->
					<thead>
					<tr>
						<th class="font-weight-bold">
						<strong>#</strong>
						</th>
						<th class="font-weight-bold">
						<strong>Item</strong>
						</th>
						<th class="font-weight-bold">
						<strong>Size</strong>
						</th>

						<th class="font-weight-bold">
							<strong>Colour</strong>
						</th>
						
						<th class="font-weight-bold">
						<strong>Price</strong>
						</th>
						<th class="font-weight-bold">
						<strong>QTY</strong>
						</th>
						<th class="font-weight-bold">
						<strong>Total Price</strong>
						</th>
						<th></th>
					</tr>
					</thead>
					<!-- Table head -->
					<!-- Table body -->
					<tbody>
					{% for order_item in cart_items %}
					<tr>
						<td class="font-weight-bold">
						{{forloop.counter}}
						</td>
						<th scope="row">
							<div class='row'>
								<div class='w-my col-lg-8 col-sm-12 col-md-12'>
									<h5 class="mt-3">
										<a>{{order_item.item.title}}</a>
									</h5>
									
								</div>
							</div>
						</th>
						<td>{{order_item.size}}</td>
						<td>{{order_item.color}}</td>
						
						{% if order_item.item.discount_price %}
						<td>Rs. {{order_item.item.discount_price}}  <s><small>{{order_item.item.price}}</small></s></td>
						{% else %}
						<td>Rs. {{order_item.item.price}}</td>
						{% endif %}
						<td class="text-center text-md-left">
						<span class="qty">{{order_item.quantity}}</span>
						<div class="btn-group radio-group ml-2">
							<a href="{% url 'products:decrement' order_item.pk %}" class="btn btn-sm btn-primary btn-rounded">
							&mdash;
							</a>
							<a href="{% url 'products:increment' order_item.pk %}" class="btn btn-sm btn-primary btn-rounded">
							+
							</a>
						</div>
						</td>
						<td class="font-weight-bold">
							<strong>
							{% if order_item.item.discount_price %}
									Rs. {{order_item.get_discount_total_price}} <s><small>{{order_item.get_item_total_price}}</small></s>
								{% else %}
									Rs. {{order_item.get_item_total_price}}
								{% endif %}
							</strong>
						</td>
						<td>
						<a href="{% url 'products:remove_from_cart' order_item.pk %}" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="top"
							title="Remove item">X
						</a>
						</td>
					</tr>
					<!-- First row -->

					{% empty %}
						<tr>
							<td colspan="7">Your Cart is empty</td>
						</tr>
						<tr>	
							<td colspan="7">
								
								<a class="btn btn-warning float-right" href="{% url 'products:list_products' %}">Continue Shopping
								</a>
							</td>
						</tr>
					{% endfor %}
					{% if total_price %}
						<tr>
							<td colspan="4"></td>
							<td><b>Order Total</b></td>
							<td><b>Rs. {{total_price}}</b></td>
							<td></td>
						</tr>
						<tr>
							<td colspan="7">
								<a class="btn btn-warning float-right ml-2" href="{% url 'products:list_products' %}">Continue Shopping
								</a>
								<a class="btn btn-warning float-right" href="{% url 'orders:checkout' %}">Checkout
								</a>
							</td>
						</tr>
						{% endif %}
					</tbody>
					<!-- Table body -->
				</table>
				</div>
				<!-- Shopping Cart table -->

			</section>
		</div>
	</div>

</div>

{% endblock content %}

products/templates/product_detail.html
{% extends 'base.html' %}

{% block content %}
<style>
  {% for color in product.colors.all %}
  .color-{{forloop.counter}}{
      background-color: {{color.colorcode}};
      border:1px solid grey;
  }
  
  {% endfor %}
  
  
  </style>

  <!--Main layout-->
  <main class="mt-5">
    <div class="mt-5 pt-3">
      
      <!--Grid row-->
      <div class="row wow fadeIn mx-5">
        

        <!--Grid column-->
        <div class="col-lg-6 mb-4">
          <a class="link-text mx-2" href="/"><b>Home</b></a>> <a class="link-text" href="/all_product/?c={{product.category.pk}}"><b>{{product.category.name}}</b></a> > {{product.title}}
          <div class="mb-2 py-5">
            

            <a href="{{product.image.url}}" data-lightbox="example-set" data-title="{{product.title}}">
              <img class="card-img-top" style="display: block;
              margin-left: auto;
              margin-right: auto;
              width: 70%;" src="{{product.image.url}}" alt="item-pic"/>
            </a>
          </div>
        
            

          <div class='row'>
            {% if product.image_1 %}
            <div class='col-md-3 col-sm-3 col-3'>
              <div class="product-img zoom">
                <a href="{{product.image_1.url}}" data-lightbox="example-set" data-title="{{product.title}}">
                  <img class="card-img-top" src="{{product.image_1.url}}" alt="item-pic"/>
                </a>
              </div>
            </div>
            {% endif %}
            {% if product.image_2 %}
            <div class='col-md-3 col-sm-3 col-3'>
              <div class="product-img zoom">
                <a href="{{product.image_2.url}}" data-lightbox="example-set" data-title="{{product.title}}">
                  <img class="card-img-top" src="{{product.image_2.url}}" alt="item-pic"/>
                </a>
              </div>
            </div>
            {% endif %}
            {% if product.image_3 %}
            <div class='col-md-3 col-sm-3 col-3'>
              <div class="product-img zoom">
                <a href="{{product.image_3.url}}" data-lightbox="example-set" data-title="{{product.title}}">
                  <img class="card-img-top" src="{{product.image_3.url}}" alt="item-pic"/>
                </a>
              </div>
            </div>
            {% endif %}
            
            {% if product.image_4 %}
            <div class='col-md-3 col-sm-3 col-3'>
              <div class="product-img zoom">
                <a href="{{product.image_4.url}}" data-lightbox="example-set" data-title="{{product.title}}">
                  <img class="card-img-top" src="{{product.image_4.url}}" alt="item-pic"/>
                </a>
              </div>
            </div>
            {% endif %}
          </div>
          

        </div>

        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-6 mb-4">
          <div class='row'>
            <div class='py-5'>

          <!--Content-->
              <div class="p-4 mb-4">
                <form action="{% url 'products:add_to_cart' %}" id='form1' method='POST'>

                {% csrf_token %}


                  <input type='hidden' name='pk' value='{{product.pk}}'>
                  <div class='title-font-d pb-2'>

                  <b>{{product.title}}</b>
                  </div>
                  <!-- <hr style="position: relative; 
                  top: 0px; 
                  border: none; 
                  height: 1px;
                  background: black; 
                  margin-bottom: 15px; "> -->

                  <p class="lead">
                    <span class="font-weight-bold">
                          {% if product.discount_price %}
                          <span class="money-d">₹ {{product.discount_price|floatformat:0}}</span>
                          
                      
                          <span class='money-strike-d'>₹<s> {{product.price|floatformat:0}}</s></span>

                          <span style='color:red;'><small>{{product.get_discount_percentage}}% discount</small></span>
                          
                          {% else %}
                          <span class="money-d">₹ {{product.price|floatformat:0}}</span>
                
                          {% endif %}
                    </span>
                    <small><br>(Inclusive of all taxes.)</small>
                  </p>
                  {% if product.is_in_stock %}
                  <p>In Stock</p>
                  {% else %}
                  <p style="color: red;">Out of Stock</p>
                  {% endif %}

            {% if product.sizes %}
                  
                  <div class='form-group size' id='size'>
                    <div class='label-size'>Select Size: <span id='size-label'></span>
                    
                    </div>
                  </div>
                  <div>
                    {% for size in product.sizes %}
                      <a class="al">{{size}}</a>
                    {% endfor %}
                  </div>
                  <div class="my-2">
                    <a href="{% url 'products:size' %}" class='link-text'><b><u>Check Size Guide</u></b></a>
                  </div>
          {% endif %}
          {% if product.colors.all %}

                  <div class='mt-3'>
                    <label class='label-size'>Select Colour: <span id='color-label'></span></label>
                </div>
                  
                <div class='mb-4'>
                  {% for color in product.colors.all %}
                    
                    <a class='color-{{forloop.counter}} cl' id='{{color}}' data-toggle="tooltip" data-placement="bottom" title='{{color}}'></a>
                  {% endfor %}
                </div>
          {% endif %}

                  

                  <div class='mt-3'>
                      <label for='qty' class='label-size'>Qty:</label>
                  </div>
                    
                  <div class='mb-4'>
                    <input class='form-control' style='width:50px;' type="number" id="qty" name="quantity" min="1" max='9'
                      value="1" required>
                  </div>

                  {% if product.is_in_stock %}
                  <p>Free Shipping</p>
                  <button type='submit' class="btn btn-dark btn-md mx-0 mb-4">
                    Add to cart
                  <i class="fas fa-shopping-cart ml-1"></i>
                  </button>
                  {% else %}
                  

                  {% endif %}
                  
                  


                  
                  

                  <div>
                    <h4>Description</h4>
                    <!-- <hr style="position: relative; 
                  top: 0px; 
                  border: none; 
                  height: 1px;
                  background: black; 
                  margin-bottom: 15px; "> -->
                  {% if product.description %}
                    <p>{{product.description}}</p>
                  {% endif %}
                  </div>
                  {% if product.color %}
                  <div >
                    <label class='label-size'>Colour</label>
                    <p>{{product.color}}</p>
                  </div>
                  {% endif %}
                  {% if product.material %}
                  <div >
                    <label class='label-size'>Material</label>
                    <p>{{product.material}}</p>
                  </div>
                  {% endif %}
                  {% if product.stretchability %}
                  <div >
                    <label class='label-size'>Stretchability</label>
                    <p>{{product.stretchability}}</p>
                  </div>
                  {% endif %}
                  {% if product.disclaimer %}
                  <div >
                    <label class='label-size'>Disclaimer</label>
                    <p>{{product.disclaimer}}</p>
                  </div>
                  {% endif %}

                  

                </form>


          
              </div>
          <!--Content-->
            </div>
            
          </div>

        </div>
        <!--Grid column-->

       

      </div>
      <!--Grid row-->


    </div>
  </main>
  <!--Main layout-->
{% endblock content %}


{% block script %}

{% if product.colors.all %}
    {% if product.sizes %}

      <script>
        var size='Nn';
        var color='Nn';
        var sp = 0;
        var cp = 0;

          $(".al").click(function(e){
            $(".al").removeClass("al-active")
            $(this).addClass("al-active")
            size = $(this).html()
            $('#size-label').html(size)
          })

          $(".cl").click(function(e){
            $(".cl").removeClass("cl-active")
            $(this).addClass("cl-active")
            color = $(this).attr('id')
            $('#color-label').html(color)
          })
          $(document).on('submit', '#form1', function (e) {
            if (size=='Nn'){
              $('#size-label').html('Please select size!')
              sp = 0
            }
            else{
              sp = 1
            }
            if (color=='Nn'){
              $('#color-label').html('Please select colour!')
              cp = 0
            }
            else{
              cp = 1
            }
            if (cp == 1 && sp == 1) {
              $("<input />").attr("type", "hidden")
                  .attr("name", "size")
                  .attr("value", size)
                  .appendTo("#form1");
              $("<input />").attr("type", "hidden")
                  .attr("name", "color")
                  .attr("value", color)
                  .appendTo("#form1");
              return true;
            }
            else{
              return false;
            }
          });
      </script>
    {% else %}
    <script>
      var color='Nn';
      var cp = 0;


        $(".cl").click(function(e){
          $(".cl").removeClass("cl-active")
          $(this).addClass("cl-active")
          color = $(this).attr('id')
          $('#color-label').html(color)
        })
        $(document).on('submit', '#form1', function (e) {
          if (color=='Nn'){
            $('#color-label').html('Please select colour!')
            cp = 0
          }
          else{
            cp = 1
          }
          if (cp == 1) {
            $("<input />").attr("type", "hidden")
                .attr("name", "color")
                .attr("value", color)
                .appendTo("#form1");
            return true;
          }
          else{
            return false;
          }
        });
    </script>
    {% endif %}
{% else %}
    {% if product.sizes %}

    <script>
      var size='Nn';
      var sp = 0;

        $(".al").click(function(e){
          $(".al").removeClass("al-active")
          $(this).addClass("al-active")
          size = $(this).html()
          $('#size-label').html(size)
        })

        $(document).on('submit', '#form1', function (e) {
          if (size=='Nn'){
            $('#size-label').html('Please select size!')
            sp = 0
          }
          else{
            sp = 1
          }
          if (sp == 1) {
            $("<input />").attr("type", "hidden")
                .attr("name", "size")
                .attr("value", size)
                .appendTo("#form1");
            return true;
          }
          else{
            return false;
          }
        });
    </script>

    {% else %}

    <script>


        $(document).on('submit', '#form1', function (e) {
          return true;
        });
    </script>


    {% endif %}

{% endif %}




{% endblock script %}