ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('a/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('accounts2/',include('users.urls', namespace='users')),
    path('accounts/',include('allauth.urls')),
    path('admin/',include('admindashboard.urls', namespace='a')),
    path('profile/',include('profiles.urls', namespace='profiles')),
    path('orders/', include('orders.urls', namespace='orders')),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
	path('', views.Profile.as_view(), name="menu"),
	path('your-orders/', views.CustomerOrders.as_view(), name='your-orders'),
	path('your-orders/<int:pk>/', views.CustomerOrderDetail.as_view(), name='your-order-detail'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
]

profiles/models.py
from django.db import models

# Create your models here.

profiles/views.py
from django.shortcuts import render
from django.views.generic import View
from orders.models import Order, Orderitem
from ecommerce import mixins

# Create your views here.

class Profile(mixins.LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request,'profile.html')

class CustomerOrders(mixins.LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        orders = Order.objects.filter(customer=request.user, confirm=True).order_by('-timestamp')
        context = {
            'orders':orders,
        }
        return render(request, 'customer_orders.html', context)


class CustomerOrderDetail(mixins.LoginRequiredMixin, mixins.CustomerRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        order = Order.objects.get(pk=pk)
        context = {
            'order':order,
        }
        return render(request, 'customer_order_detail.html', context)

profiles/templates/customer_order_detail.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
  <!--Main layout-->
<div class="container">
        <div class="row pt-4 justify-content-center">

            <!-- Content -->
            <div class="col-lg-10 col-sm-12 col-md-12">

                <section class="section pt-4">
                    <h4 class="font-weight-bold mt-4 dark-grey-text"><strong>Your Order Details</strong></h4>
                    <hr class="mb-5">

                    <div class="card mt-4">
                      <h5 class="card-header h5">Order #{{order.order_id}}</h5>

                      <div class="card-body" style='overflow-x:auto;'>
                        {% for orderitem in order.orderitem_set.all %}
                          <table class="table">

                              <thead>
                                <tr>
                                  <th>
                                    <div class='w-my'>
                                      <img src="{{orderitem.item.image.url}}" alt="Image"
                                        class="img-fluid z-depth-0" width="50px" height="50px">
                                    </div>
                                  </th>
                                  <th>
                                    <h5 class="card-title">{{orderitem.item_name}}</h5>
                                  </th>
                                </tr>
                              </thead>
               
                              <tbody>

                                {% if orderitem.size %}
                              
                                
                                <tr>
                                  <td class="card-text">Size:</td>
                                  <td class="card-text">{{orderitem.size}}</td>
                                </tr>
                                {% endif %}
                                {% if orderitem.color %}

                                <tr>
                                  <td class="card-text">Colour:</td>
                                  <td class="card-text">{{orderitem.color}}</td>
                                </tr>
                                {% endif %}
                                <tr>
                                  <td class="card-text">Quantity:</td>
                                  <td class="card-text">{{orderitem.quantity}}</td>
                                </tr>
                                <tr>
                                  <td class="card-text">Price:</td>
                                  <td class="card-text">{{orderitem.price_total}}</td>
                                </tr>
                              </tbody>
                            </table>
                        {% endfor %} 
                        </div>
                        <div class="card-body" style='overflow-x:auto;'>

                        <table class="table">
                              <tbody>
                                <tr>
                                  <td class="card-text">Total Price:</td>
                                  <td class="card-text">Rs. {{order.total}}</td>
                                </tr>
                                
                                <tr>
                                  <td class="card-text">Status:</td>
                                  <td>
                                  {% if order.is_paid %}
                            <span class="badge badge-success">Payment Success</span>
                        {% else %}
                            <span class="badge badge-warning">Payment Failed</span>
                        {% endif %}
                                  </td>
                                </tr>
                                {% if order.transaction_id %}
                                <tr>
                                  <td class="card-text">Transaction ID:</td>
                                  <td class="card-text">{{order.transaction_id}}</td>
                                </tr>
                                {% endif %}
                              </tbody>
                            </table>   
                      </div>
                    </div>
                </section>

            </div>
            <!-- /.Content -->

        </div>
</div>
                    
{% endblock content %}

profiles/templates/customer_orders.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
  <!--Main layout-->
<div class="container">
        <div class="row pt-4 justify-content-center">

            <!-- Content -->
            <div class="col-lg-10 col-sm-12 col-md-12">

                <section class="section pt-4">
                    <h4 class="font-weight-bold mt-4 dark-grey-text"><strong>Your Orders</strong></h4>
                    <hr class="mb-5">
                    {% for order in orders %}

                    <div class="card mt-4">
                      <h5 class="card-header h5">Order #{{order.order_id}}</h5>
                      <div class="card-body over-x-auto">
                        <table class="table">
                              <tbody>
                                <tr>
                                  <td class="card-text">Total Price:</td>
                                  <td class="card-text">Rs. {{order.total}}</td>
                                </tr>
                               

                                <tr>
                                  <td class="card-text">Status:</td>
                                  <td>{% if order.is_paid %}
                            <span class="badge badge-success">Payment Success</span>
                        {% else %}
                            <span class="badge badge-warning">Payment Failed</span>
                        {% endif %}


                                  </td>
                                </tr>


                                {% if order.transaction_id %}
                                <tr>
                                  <td class="card-text">Transaction ID:</td>
                                  <td class="card-text">{{order.transaction_id}}</td>
                                </tr>
                                {% endif %}
                              </tbody>
                            </table>   
                          
                        <a href="{% url 'profile:your-order-detail' pk=order.pk %}" class="btn btn-dark">See Details</a>
                      </div>
                    </div>

                    {% endfor %}

                </section>

            </div>
            <!-- /.Content -->

        </div>
</div>
                    
{% endblock content %}

profiles/templates/profile.html
{% extends 'base.html' %}

{% block content %}
  <!--Main layout-->
<div class="container">
        <div class="row pt-4 justify-content-center">
            <div class="col-lg-6 col-sm-12 col-md-12">


                <section class="section pt-4">
                    <h4 class="font-weight-bold mt-4 dark-grey-text"><strong>Your Account</strong></h4>
                    <hr class="mb-5">

                    <section>
                                        <!--Card-->
                        <div class="card card-ecommerce mb-4">
                            <div class="view overlay">
                                <div class="card-body text-center">      
                                    <h5 class="card-title mb-1"><strong>Your Orders</strong></h5>
                                </div>
                                <a href='{% url 'profiles:your-orders' %}'>
                                    <div class="mask rgba-white-slight waves-effect waves-light"></div>
                                </a>
                            </div>
                        </div>
                        
                        <div class="card card-ecommerce mb-4">
                            <div class="view overlay">
                                <div class="card-body text-center">      
                                    <h5 class="card-title mb-1"><strong>Change Password</strong></h5>
                                </div>
                                <a href='/accounts/password/change/'>
                                    <div class="mask rgba-white-slight waves-effect waves-light"></div>
                                </a>
                            </div>
                        </div>



                    </section>

                </section>
            </div>

        </div>
</div>
<br><br><br><br>
                    
{% endblock content %}
  