admindashboard/urls.py
from django.urls import path
from . import views

app_name = 'a'

urlpatterns = [
	path('dashboard/', views.Orders.as_view(), name = 'dashboard'),
	path('orders/<int:pk>/', views.OrdersDetail.as_view(), name = 'orders-detail'),
	path('create-item/', views.Items.as_view(), name='item-create'),
	path('items/', views.ItemsDisplay.as_view(), name='item-list'),
	path('items/edit/<int:pk>/', views.ItemUpdate.as_view(), name='item-edit'),
	path('items/delete/<int:pk>/', views.ItemDelete.as_view(), name='item-delete'),
	path('contacts/', views.ContactsList.as_view(), name='contacts-list'),
	path('contacts/<int:pk>/', views.ContactsDetail.as_view(), name = 'contacts-detail'),
	path('add-color/', views.AddColor.as_view(), name = 'color-create'),
	path('colors/', views.Colors.as_view(), name = 'colors'),





]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('a/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('accounts2/',include('users.urls', namespace='users')),
    path('accounts/',include('allauth.urls')),
    path('admin/',include('admindashboard.urls', namespace='a')),
    path('profile/',include('profiles.urls', namespace='profiles')),
    path('orders/', include('orders.urls', namespace='orders')),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
	path('', views.ProductsList.as_view(), name = 'list_products'),
	path('all_product/', views.All_ProductsList.as_view(), name = 'all_products'),
	path('product_detail/<int:pk>/', views.ProductDetail.as_view(), name = 'product_detail'),
	path('cart/', views.CartList.as_view(), name='cart'),
	path('contact/', views.ContactFormPage.as_view(), name='contact-us'),
	path('terms_condition/', views.Terms_Condition, name = 'terms_condition'),
	path('privacy_policy/', views.Privacy_Policy, name = 'privacy_policy'),
	path('about_us/', views.about_us, name = 'about_us'),
	path('shipping_policy/', views.return_refund, name = 'return_refund'),
	path('how_to_buy/', views.how_to_buy, name = 'how_to_buy'),
	path('exchange/', views.exchange, name = 'exchange'),
	path('size_chart/', views.size, name = 'size'),
	path('add-to-cart/', views.AddToCart.as_view(), name = 'add_to_cart'),
	path('increment/<int:pk>/', views.IncrementCart.as_view(), name = 'increment'),
	path('decrement/<int:pk>/', views.DecrementCart.as_view(), name = 'decrement'),
	path('remove-from-cart/<int:pk>/', views.DeleteFromCart.as_view(), name='remove_from_cart'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profile'

urlpatterns = [
	path('', views.Profile.as_view(), name="menu"),
	path('your-orders/', views.CustomerOrders.as_view(), name='your-orders'),
	path('your-orders/<int:pk>/', views.CustomerOrderDetail.as_view(), name='your-order-detail'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
]

products/models.py
from django.db import models
from django.shortcuts import reverse
from django.conf import settings
from django.db.models import Sum
from multiselectfield import MultiSelectField
from ecommerce.storage_backends import MediaStorage


# Create your models here.
user = settings.AUTH_USER_MODEL
LABEL_CHOICES = (
    ('N', 'New Arrivals (Show on Top)'),
)

SIZE_CHOICES = (
    ('XS', 'XS'),
    ('S', 'S'),
    ('M', 'M'),
    ('L', 'L'),
    ('XL', 'XL'),
    ('34', '34'),
    ('35', '35'),
    ('36', '36'),
    ('37', '37'),
    ('38', '38'),
    ('39', '39'),
    ('40', '40'),
    ('41', '41'),
    ('42', '42'),
    ('43', '43'),
)

class Color(models.Model):
    colorcode = models.CharField(max_length=50)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Item(models.Model):
    title = models.CharField(max_length=100)
    image = models.FileField(storage=MediaStorage(), upload_to='item_images')
    image_1 = models.FileField(storage=MediaStorage(), upload_to='item_images', blank=True)
    image_2 = models.FileField(storage=MediaStorage(), upload_to='item_images', blank=True)
    image_3 = models.FileField(storage=MediaStorage(), upload_to='item_images', blank=True)
    image_4 = models.FileField(storage=MediaStorage(), upload_to='item_images', blank=True)
    is_in_stock = models.BooleanField(default=True)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, blank=True)
    colors = models.ManyToManyField(Color, blank=True)
    sizes = MultiSelectField(choices=SIZE_CHOICES, max_length=100, blank=True)
    stretchability = models.CharField(max_length=1000, blank=True, null=True)
    material = models.CharField(max_length=1000, blank=True, null=True)
    color = models.CharField(max_length=1000, blank=True, null=True)
    disclaimer = models.TextField(blank=True, null=True)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("a:item-list")
    
    def get_discount_percentage(self):
        return int(((self.price - self.discount_price)/self.price)*100)


class Cart(models.Model):
    user = models.OneToOneField(user, on_delete=models.CASCADE, related_name='cart')
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total_price(self):
        total = 0
        for item in self.cartitem_set.all():
            total += item.get_final_price()
        return total

    def get_items_count(self):
        return self.cartitem_set.all().aggregate(Sum('quantity'))['quantity__sum']


class Cartitem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    size = models.CharField(choices=SIZE_CHOICES, max_length=100, blank=True)
    color = models.CharField(max_length=100, blank=True)
    quantity = models.IntegerField(default=1)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.quantity} of {self.item.title} for {self.cart.user.username}"

    def get_item_total_price(self):
        return self.item.price * self.quantity

    def get_discount_total_price(self):
        return self.item.discount_price * self.quantity

    def get_item_final_price(self):
        if self.item.discount_price:
            return self.item.discount_price * self.quantity
        else:
            return self.item.price * self.quantity

    def get_item_final_price_single(self):
        if self.item.discount_price:
            return self.item.discount_price
        else:
            return self.item.price

    def get_amount_saved(self):
        return self.get_item_total_price() - self.get_discount_total_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_discount_total_price()
        return self.get_item_total_price()
    
    def increment(self):
        self.quantity = self.quantity + 1

    def decrement(self):
        self.quantity = self.quantity - 1

products/views.py
from django.shortcuts import render
from . models import Item, Category, Cart, Cartitem
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.views.generic import View
from ecommerce.mixins import LoginRequiredMixin
from admindashboard.forms import ContactForm
from django.core.mail import EmailMessage
from django.conf import settings
import requests
import json
from django.urls import reverse

# Create your views here.


class ProductsList(ListView):
    template_name = 'home.html'
    model = Item
    paginate_by = 8
    context_object_name = 'products'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_superuser:
            return redirect('a:dashboard')
        else:
            return super().dispatch(request, *args, **kwargs)


    def get_queryset(self):
        queryset = super(ProductsList, self).get_queryset()
        q1 = queryset.filter(label='N')  # 
        return q1

    def get_context_data(self, **kwargs):
        context = super(ProductsList, self).get_context_data(**kwargs)
        context['p1'] = Category.objects.get(name="Tops & Blouses")
        context['p2'] = Category.objects.get(name="Dresses")
        context['p3'] = Category.objects.get(name="Jumpsuits")
        context['p4'] = Category.objects.get(name="Co ord's")
        context['p5'] = Category.objects.get(name="Bottoms")
        context['p6'] = Category.objects.get(name="Winter")
        return context



class All_ProductsList(ListView):
    template_name = 'all_product.html'
    model = Item
    paginate_by = 20
    context_object_name = 'products'
    title = 'All'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_superuser:
            return redirect('a:dashboard')
        else:
            return super().dispatch(request, *args, **kwargs)


    def get_queryset(self):
        queryset = super(All_ProductsList, self).get_queryset()
        c = self.request.GET.get('c',None)
        if c is not None:
            queryset = queryset.filter(category__pk=c)
            self.title = Category.objects.get(pk=c).name
        name = self.request.GET.get('name',None)
        if name is not None:
            queryset1 = queryset.filter(title__icontains=name)
            queryset2 = queryset.filter(category__name__icontains=name)
            queryset4 = queryset.filter(description__icontains=name)
            queryset = (queryset1 | queryset2 | queryset4).distinct()
            self.title = "Results for '"+ name +"'"
        label = self.request.GET.get('l',None)
        if label is not None:
            queryset = queryset.filter(label=label)
            self.title = 'New Arrivals'
        n = self.request.GET.get('n',None)
        if n is not None:
            if n == 'C':
                queryset = super(All_ProductsList, self).get_queryset()
                categories = ['Tops & Blouses','Dresses', 'Jumpsuits', "Co ord's", 'Bottoms', 'Winter']
                self.title = 'All Clothing'
                queryset = queryset.filter(category__name__in = categories)
            if n == 'A':
                queryset = super(All_ProductsList, self).get_queryset()
                categories = ['Footwear','Bags', 'Jewellery']
                self.title = 'All Accessories'
                queryset = queryset.filter(category__name__in = categories)
        queryset = queryset.order_by('title')
        s = self.request.GET.get('s',None)
        if s is not None:
            if s == 'atoz':
                queryset = queryset.order_by('title')
            if s == 'ztoa':
                queryset = queryset.order_by('-title')
            if s == 'p1':
                queryset = queryset.order_by('price')
            if s == 'p2':
                queryset = queryset.order_by('-price')

        return queryset

    def get_context_data(self, **kwargs):
        context = super(All_ProductsList, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['title'] = self.title
        return context





class CartList(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user_cart, _ = Cart.objects.get_or_create(user=request.user)
        data = {
            'cart_items':user_cart.cartitem_set.all(),
            'total_price':user_cart.get_total_price()
        }
        return render(request, 'order_summary.html', context=data)



class ProductDetail(View):
    def get(self, request, pk, *args, **kwargs):
        product = get_object_or_404(Item, pk=pk)
        
        return render(request, 'product_detail.html', {'product': product})

class AddToCart(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        item = Item.objects.get(pk=(request.POST.get('pk')))
        if not item.is_in_stock:
            messages.error(request, 'Item Out of stock')
            return redirect('products:product_detail', pk=item.pk)
        size = request.POST.get('size',None)
        color = request.POST.get('color',None)
        quantity = int(request.POST.get('quantity','1'))
        user_cart, _ = Cart.objects.get_or_create(user=request.user)
        if size is not None:
            if color is not None:
                cart_item = user_cart.cartitem_set.all().filter(item=item, size=size, color=color)
            else:
                cart_item = user_cart.cartitem_set.all().filter(item=item, size=size)
        else:
            if color is not None:
                cart_item = user_cart.cartitem_set.all().filter(item=item, color=color)
            else:
                cart_item = user_cart.cartitem_set.all().filter(item=item)


        if cart_item.exists():
            cart_item = cart_item.first()
            for i in range(quantity):
                cart_item.increment()
            cart_item.save()
        else:
            if size is not None:
                if color is not None:
                    cart_item = Cartitem.objects.create(item=item, size=size ,cart=user_cart, color=color, quantity=quantity)
                else:
                    cart_item = Cartitem.objects.create(item=item, size=size ,cart=user_cart, quantity=quantity)
            else:
                if color is not None:
                    cart_item = Cartitem.objects.create(item=item, cart=user_cart, color=color, quantity=quantity)
                else:
                    cart_item = Cartitem.objects.create(item=item ,cart=user_cart, quantity=quantity)

        messages.info(request, 'Item is added to your cart')
        return redirect('products:cart')

class IncrementCart(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        cart_item = Cartitem.objects.get(pk=pk)
        if not cart_item.item.is_in_stock:
            cart_item.delete()
            messages.error(request, 'Item Out of stock')
            return redirect('products:cart')
        
        cart_item.increment()
        cart_item.save()
        messages.info(request, 'Item has been added to your cart')
        return redirect('products:cart')

class DecrementCart(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        cart_item = Cartitem.objects.get(pk=pk)
        if not cart_item.item.is_in_stock:
            cart_item.delete()
            messages.error(request, 'Item Out of stock')
            return redirect('products:cart')
        cart_item.decrement()
        cart_item.save()
        if cart_item.quantity == 0:
            cart_item.delete()
        messages.info(request, 'Item has been removed from your cart')
        return redirect('products:cart')


class DeleteFromCart(LoginRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        cart_item = Cartitem.objects.get(pk=pk)
        cart_item.delete()
        messages.info(request, 'Item has been removed from your cart')
        return redirect('products:cart')

class ContactFormPage(View):
    def get(self, request, *args, **kwargs):
        context = {
            'form':ContactForm,
        }
        return render(request, 'contact_us.html', context)
    
    def post(self, request, *args, **kwargs):
        form = ContactForm(request.POST, request.FILES)
        if form.is_valid():
            c = form.save()
        context = {
            'form':form
        }
        return render(request, 'contact_us.html', context)


def Terms_Condition(request):
    return render(request, 'terms_condition.html')


def Privacy_Policy(request):
    return render(request, 'privacy_policy.html' )

def about_us(request):
    return render(request, 'about_us.html')

def return_refund(request):
    return render(request, 'return_refund.html')

def exchange(request):
    return render(request, 'exchange.html')

def size(request):
    return render(request, 'size.html')

def how_to_buy(request):
    return render(request, 'how_to_buy.html')

products/templates/includes/admin_navbar.html
{% load static %}
{% load cart_template_tags %}
<nav class="navbar navbar-expand-lg fixed-top navbar-light white" style="box-shadow: unset;">
    <div class="container">

    
      <!-- Brand -->
      <a class="navbar-brand mx-auto" href="{% url 'products:list_products' %}">
        <div class="nav-control">
          <img src="{% static 'images/logo.png'%}" width="100%" alt="">
          
        </div>
        
      </a>



      <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

      <!-- Links -->


    </div>
  </nav>

  <nav class="navbar fixed-top navbar-expand-lg navbar-light justify-content-center" style="top: 75px; background-color: #efefef; padding: 0; box-shadow: unset;">

    <ul class="nav justify-content-center lighten-4">
      <li class="nav-item">
        <a href="/" type="button" class="btn btn-flat" style="margin: 0; box-shadow: unset;">Orders</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'a:contacts-list' %}" type="button" class="btn btn-flat" style="margin: 0; box-shadow: unset;">Contact Forms</a>
      </li>
      
      
      <li class="nav-item">
        <a href="{% url 'a:item-list' %}" type="button" class="btn btn-flat" style="margin: 0; box-shadow: unset; ">Items</a>
      </li>

      <li class="nav-item">
        <a href="{% url 'a:colors' %}" type="button" class="btn btn-flat" style="margin: 0; box-shadow: unset; ">Colours</a>
      </li>
  

      <li class="nav-item">
        <a href="/accounts/logout/" type="button" class="btn btn-flat" style="margin: 0; box-shadow: unset; ">Logout</a>
      </li>
  
   
    </ul>
    
  </nav>

products/templates/includes/footer.html
{% load static %}
<style>
  .white-bg{
    background-color: white;
    color: black;
  }
</style>
  <!-- Footer -->


<footer class="font-small mt-4">

  <!-- Footer Links -->
  <div class="container text-center text-md-left">
    <hr>

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-3 mx-auto">

        <!-- Links -->
        <h5 class="mt-3 footer-head" style="font-weight: 450;">Contact Us</h5>
        <div class='c2 mobile-hider'></div>
        <div class='c2 mx-auto mobile-viewer'></div>
        <ul class="list-unstyled mt-2">
          <li>
            <p>For any queries or order updates get in touch with our team at:</p>
            <p>Email: <a class="link-text" href="mailto:buy@cozylabel.in"><b>buy@cozylabel.in</b></a></p>
            
          </li>
          <li>
            <a class=" link-text" href="https://www.facebook.com/thecozylabel"><i class="fab fa-x fa-facebook pr-2"></i>Facebook</a>
          </li><br>
          <li>
            <a class=" link-text" href="https://www.instagram.com/thecozylabel/"><i class="fab fa-x fa-instagram pr-2"></i>Instagram</a>
          </li><br>
          <li>
            <a class=" link-text" href="whatsapp://send?phone=+919390198581"><i class="fab fa-x fa-whatsapp pr-2"></i>9390198581</a>
          </li><br>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">
      

      <!-- Grid column -->
      <div class="col-md-3 mx-auto">

        <!-- Links -->
        <h5 class="mt-3 footer-head" style="font-weight: 450;">Quick Links</h5>
        <div class='c2 mobile-hider'></div>
        <div class='c2 mx-auto mobile-viewer'></div>
        <ul class="list-unstyled mt-2">

          <li class="mb-2">
            <a href="{% url 'products:about_us' %}" class='link-text-footer'>About Us</a>
          </li>

          <li class="mb-2">
            <a href="{% url 'products:how_to_buy' %}" class='link-text-footer'>How to buy</a>
          </li>
          <li class="mb-2">
            <a href="{% url 'products:size' %}" class='link-text-footer'>Size Guide</a>
          </li>
          <li class="mb-2">
            <a href="{% url 'products:return_refund' %}" class='link-text-footer'>Shipping Policy</a>
          </li>

          <li class="mb-2">
            <a href="{% url 'products:exchange' %}" class='link-text-footer'>Exchange and Returns</a>
          </li>
          <li class="mb-2">
            <a href="{% url 'products:privacy_policy' %}" class='link-text-footer'>Privacy Policy</a>
          </li>
          <li class="mb-2">
            <a href="{% url 'products:terms_condition' %}" class='link-text-footer'>Terms and Conditions</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

       <!-- Grid column -->
      <div class="col-md-3 mx-auto">

        <h5 class="mt-3 footer-head" style="font-weight: 450;">News letters</h5>
        <div class='c2 mobile-hider'></div>
        <div class='c2 mx-auto mobile-viewer'></div>
        
        <ul class="list-unstyled mt-2">
          <li>
            <p>Subscribe to receive updates, access to exclusive deals, and more.</p>
            <form>
              <input type='text' />
              <button type="button" class='btn btn-sm btn-dark ml-0 mt-2'>Submit</button>
            </form>
          </li><br>
          
        </ul>


      </div>
      <!-- Grid column -->



    </div>
    <!-- Grid row -->
    <hr>
    

  </div>
  <!-- Footer Links -->


  <!-- Copyright -->
  <div class="text-center white-bg">
    
    <div class='olo mb-2'>
      <img src="{% static 'images/logo.png'%}">
     
  </div><p>© 2020 Copyright:
    TheCozyLabel Pvt Ltd. All Rights Reserved</p>
     <p>Made by <a class="link-text" href="https://avasyutech.com/"><b>AvasyuTech</b></a></p>
  </div>

</footer>
<!-- Footer -->