admindashboard/urls.py
from django.urls import path
from . import views

app_name = 'a'

urlpatterns = [
	path('dashboard/', views.Orders.as_view(), name = 'dashboard'),
	path('orders/<int:pk>/', views.OrdersDetail.as_view(), name = 'orders-detail'),
	path('create-item/', views.Items.as_view(), name='item-create'),
	path('items/', views.ItemsDisplay.as_view(), name='item-list'),
	path('items/edit/<int:pk>/', views.ItemUpdate.as_view(), name='item-edit'),
	path('items/delete/<int:pk>/', views.ItemDelete.as_view(), name='item-delete'),
	path('contacts/', views.ContactsList.as_view(), name='contacts-list'),
	path('contacts/<int:pk>/', views.ContactsDetail.as_view(), name = 'contacts-detail'),
	path('add-color/', views.AddColor.as_view(), name = 'color-create'),
	path('colors/', views.Colors.as_view(), name = 'colors'),





]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('a/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('accounts2/',include('users.urls', namespace='users')),
    path('accounts/',include('allauth.urls')),
    path('admin/',include('admindashboard.urls', namespace='a')),
    path('profile/',include('profiles.urls', namespace='profiles')),
    path('orders/', include('orders.urls', namespace='orders')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
]

admindashboard/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=200)
    message = models.CharField(max_length=200000)
    image = models.FileField(upload_to='contact_forms', blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

admindashboard/forms.py
from django import forms
from products.models import Item, Category, Color
from .models import Contact

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['email','name','message','image']


class ColorForm(forms.ModelForm):
    class Meta:
        model = Color
        fields = ['colorcode','name']

admindashboard/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from orders.models import Order
from products.models import Item, Category, Color
from ecommerce.mixins import SuperuserRequiredMixin
from django.views.generic import View, CreateView, ListView, UpdateView, DeleteView
from .forms import ItemForm, CategoryForm, ColorForm
from .models import Contact
from django.contrib import messages
# Create your views here.

class Orders(SuperuserRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        data = {
            'orders': Order.objects.filter(confirm=True).order_by('-timestamp')
        }
        return render(request, "admin_orders.html", context=data)


class OrdersDetail(SuperuserRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        data = {
            'order': Order.objects.get(pk=pk)
        }
        return render(request, "admin_orders_detail.html", context=data)

class Items(SuperuserRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        context = {
            'form':ItemForm
        }
        return render(request, 'admin_item_create.html', context)

    def post(self, request, *args, **kwargs):
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('a:item-list')
        context = {
            'form':ItemForm(request.POST, request.FILES)
        }
        messages.error(request, 'some error')
        return render(request, 'admin_item_create.html', context)


class ItemUpdate(SuperuserRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        context = {
            'form':ItemForm(instance=Item.objects.get(pk=pk))
        }
        return render(request, 'admin_item_update.html', context)

    def post(self, request, pk,  *args, **kwargs):
        form = ItemForm(request.POST, request.FILES, instance=Item.objects.get(pk=pk))
        if form.is_valid():
            form.save()
            return redirect('a:item-list')
        context = {
            'form':ItemForm(request.POST, request.FILES)
        }
        return render(request, 'admin_item_update.html', context)
    



class ItemsDisplay(SuperuserRequiredMixin, ListView):
    model = Item
    template_name = 'admin_item_list.html'
    context_object_name = 'items'



class ItemDelete(SuperuserRequiredMixin, DeleteView):
    model = Item
    template_name = 'admin_item_delete.html'
    success_url = reverse_lazy('a:item-list')

class OrdersDelete(SuperuserRequiredMixin, DeleteView):
    model = Order
    template_name = 'admin_order_delete.html'
    success_url = reverse_lazy('a:dashboard')



class ContactsList(SuperuserRequiredMixin, ListView):
    model = Contact
    template_name = 'admin_contacts_list.html'
    fields = ['email','name','timestamp']
    context_object_name = 'contacts'
    ordering = ['-timestamp']


class ContactsDetail(SuperuserRequiredMixin, View):
    def get(self, request, pk, *args, **kwargs):
        data = {
            'contact': Contact.objects.get(pk=pk)
        }
        return render(request, "admin_contacts_detail.html", context=data)


class AddColor(SuperuserRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        context = {
            'form':ColorForm
        }
        return render(request, 'admin_color_create.html', context)

    def post(self, request, *args, **kwargs):
        form = ColorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('a:colors')
        context = {
            'form':ColorForm(request.POST)
        }
        return render(request, 'admin_color_create.html', context)


class Colors(SuperuserRequiredMixin, ListView):
    model = Color
    template_name = 'admin_colors_list.html'
    context_object_name = 'colors'

admindashboard/templates/admin_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  
  <link href="https://fonts.googleapis.com/css?family=Exo|Sen&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Baloo+2&display=swap" rel="stylesheet">
  <title>The Cozy Label</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/my-style.css' %}" rel="stylesheet">
  <link href="{% static 'css/style1.css' %}" rel="stylesheet">

  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }
    /* Chrome, Safari, Edge, Opera */
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
      -webkit-appearance: none;
      margin: 0;
    }

    /* Firefox */
    input[type=number] {
      -moz-appearance:textfield;
    }

  </style>
</head>

<body>
  {% include "includes/admin_navbar.html" %}
  
  <div class="mt-5" style="padding-top: 100px;">
  </div>


  
{% block content %}
  <!--Carousel Wrapper-->
  
  <!--Main layout-->
{% endblock content %}
      
  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

  
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">

  
  <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  
    

  </script>
  {% if messages %}
      {% for message in messages  %}
        <script>
          toastr.options = {
            "closeButton": false,
            "debug": false,
            "newestOnTop": true,
            "progressBar": true,
            "positionClass": "toast-top-center",
            "preventDuplicates": false,
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideEasing": "linear",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
          }
          toastr.{{message.tags}}('{{message}}')
        </script>
      {% endfor %}
    {% endif %}

</body>

</html>

admindashboard/templates/admin_color_create.html
{% extends 'admin_base.html' %}

{% load crispy_forms_tags %}

{% load widget_tweaks %}

{% block content %}

  <!--Main layout-->
  <main class="">
    <div class="container">

      <!--Grid row-->
      <div class="row wow fadeIn justify-content-center">

        <!--Grid column-->
        <div class="col-lg-12 col-md-12 col-sm-12 mb-4">

          <!--Card-->

            <!--Card content-->
            <div class='container'>
                <div class='row justify-content-center'>
                    <div class='col-lg-10 col-md-12 col-sm-12'>
                        <div class="card mt-4" style='width:100%; overflow-x:auto;'>
                            <h1 class='mt-4 ml-4'>Add New Color</h1>
                            <form class='card-body' method="POST" enctype="multipart/form-data">
                                {%csrf_token%}
                                {{form|crispy}}
                                
                                <button class='btn btn-primary btn-lg btn-block waves-effect waves-light' type="submit">Add</button>
                            </form>
                        </div>

                    </div>


                    

                </div>
            </div>
           


          <!--/.Card-->

        </div>
      </div>
    </div>
  </main>
{% endblock content %}

admindashboard/templates/admin_colors_list.html
{% extends 'admin_base.html' %}



{% block content %}

  <!--Main layout-->
  
<style>
{% for color in colors %}
.color-{{forloop.counter}}{
    background-color: {{color.colorcode}};
    width:15px;
    height:15px;
    border-radius:50%;
    border:1px solid grey;
}
{% endfor %}

</style>

  <main class="">
    <div class="container">

      <!--Grid row-->
      <div class="row wow fadeIn justify-content-center">

        <!--Grid column-->
        <div class="col-lg-12 col-md-12 col-sm-12 mb-4">

          <!--Card-->
          <div class="card" style='width:100%; overflow-x:auto;'>

            <!--Card content-->
            <div class="card-body">

             <table class="table">
                            <!-- Table head -->
                            <thead class="blue-grey lighten-4">
                            <tr>
                                <th>Name</th>
                                <th>Color</th>
                            </tr>
                            </thead>
                            <!-- Table head -->

                            <!-- Table body -->
                            <tbody>
                            {% for color in colors %}
                            <tr>
                                <td><b>{{color}}</b></td>
                                <td><div class='color-{{forloop.counter}}'></div></td>
                            </tr>
                            {% endfor %}
                            </tbody>
                            <!-- Table body -->
                        </table>
                      <a class='btn btn-sm btn-warning' href="{% url 'a:color-create' %}">Add New</a>



            </div>

          </div>
          <!--/.Card-->

        </div>
      </div>
    </div>
  </main>
{% endblock content %}

admindashboard/templates/admin_contacts_detail.html
{% extends 'admin_base.html' %}
{% block content %}


  <!--Main layout-->
  <main class="">
    <div class="container">

      <!--Grid row-->
      <div class="row wow fadeIn justify-content-center">

        <!--Grid column-->
        <div class="col-lg-12 col-md-12 col-sm-12 mb-4">
                 <!--Card-->
          <div class="card" style='width:100%; overflow-x:auto;'>

            <!--Card content-->
            <div class="card-body">

              <!-- Table  -->
              <table class="table">
                 <thead class="blue-grey lighten-4">
                  <tr>
                    <th colspan='2'>Contact Form Details</th>
                  </tr>
                </thead>

                <!-- Table body -->
                <tbody>
                  <tr>
                    <th scope="row">Email</th>
                    <td>{{contact.email}}</td>
                  </tr>
                  <tr>
                    <th scope="row">Name</th>
                    <td>{{contact.name}}</td>
                  </tr>
                  
                  <tr>
                    <th scope="row">Submitted Time</th>
                    <td>{{contact.timestamp}}</td>
                  </tr>
                                    
                  <tr>
                    <th scope="row">Message</th>
                    <td>{{contact.message}}</td>
                  </tr>
                  {% if contact.image %}
                  
                  <tr>
                    <th scope="row">Image</th>
                    <td><a href='{{contact.image.url}}' target='blank'><img src="{{contact.image.url}}" alt="Image"
						class="media-md img-fluid z-depth-0" width="50px" height="50px"/></a></td>
                  </tr>

                  {% endif %}
                  <tr>
                    <th scope="row"></th>
                    <td><a class='btn btn-primary waves-effect waves-light' href='mailto:{{contact.email}}'>Reply</a></td>
                  </tr>


                </tbody>
                <!-- Table body -->
              </table>
 
            </div>

          </div>
          <!--/.Card-->
        </div>
      </div>
    </div>
  </main>

{% endblock content %}

admindashboard/templates/admin_contacts_list.html
{% extends 'admin_base.html' %}



{% block content %}

  <!--Main layout-->
  <main class="">
    <div class="container">

      <!--Grid row-->
      <div class="row wow fadeIn justify-content-center">

        <!--Grid column-->
        <div class="col-lg-12 col-md-12 col-sm-12 mb-4">

          <!--Card-->
          <div class="card" style='width:100%; overflow-x:auto;'>

            <!--Card content-->
            <div class="card-body">

             <table class="table">
                            <!-- Table head -->
                            <thead class="blue-grey lighten-4">
                            <tr>
                                <th>Email</th>
                                <th>Name</th>
                                <th>Submitted at</th>
                                <th></th>
                            </tr>
                            </thead>
                            <!-- Table head -->

                            <!-- Table body -->
                            <tbody>
                            {% for contact in contacts %}
                            <tr>
                                <td>{{contact.email}}</td>
                                <td>{{contact.name}}</td>
                                <td>{{contact.timestamp}}</td>
                                <td><a class='btn btn-sm btn-primary' href="{% url 'a:contacts-detail' pk=contact.pk %}">View</a>
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                            <!-- Table body -->
                        </table>

            </div>

          </div>
          <!--/.Card-->

        </div>
      </div>
    </div>
  </main>
{% endblock content %}

admindashboard/templates/admin_item_create.html
{% extends 'admin_base.html' %}

{% load crispy_forms_tags %}

{% load widget_tweaks %}

{% block content %}

  <!--Main layout-->
  <main class="">
    <div class="container">

      <!--Grid row-->
      <div class="row wow fadeIn justify-content-center">

        <!--Grid column-->
        <div class="col-lg-12 col-md-12 col-sm-12 mb-4">

          <!--Card-->

            <!--Card content-->
            <div class='container'>
                <div class='row justify-content-center'>
                    <div class='col-lg-10 col-md-12 col-sm-12'>
                        <div class="card mt-4" style='width:100%; overflow-x:auto;'>
                            <h1 class='mt-4 ml-4'>Add Item</h1>
                            <form class='card-body' method="POST" enctype="multipart/form-data" action='{% url 'a:item-create' %}'>
                                {%csrf_token%}
                                
                                {{form|crispy}}
                                
                                <button class='btn btn-primary btn-lg btn-block waves-effect waves-light' type="submit">Add</button>
                            </form>
                        </div>

                    </div>


                    

                </div>
            </div>
           


          <!--/.Card-->

        </div>
      </div>
    </div>
  </main>
{% endblock content %}

admindashboard/templates/admin_item_delete.html
{% extends 'admin_base.html' %}



{% block content %}

  <!--Main layout-->
  <main class="">
    <div class="container">

      <!--Grid row-->
      <div class="row wow fadeIn justify-content-center">

        <!--Grid column-->
        <div class="col-lg-12 col-md-12 col-sm-12 mb-4">

          <!--Card-->
          <div class="card" style='width:100%; overflow-x:auto;'>

            <!--Card content-->
            <div class="card-body">
                <form method="POST">{% csrf_token %}
                    <p>Are you sure you want to delete "{{ object }}"?</p>
                    <input class='btn btn-danger btn-lg btn-block waves-effect waves-light' type="submit" value="Confirm">
                </form>

            </div>

          </div>
          <!--/.Card-->

        </div>
      </div>
    </div>
  </main>
{% endblock content %}

admindashboard/templates/admin_item_list.html
{% extends 'admin_base.html' %}



{% block content %}

  <!--Main layout-->
  <main class="">
    <div class="container">

      <!--Grid row-->
      <div class="row wow fadeIn justify-content-center">

        <!--Grid column-->
        <div class="col-lg-12 col-md-12 col-sm-12 mb-4">

          <!--Card-->
          <div class="card" style='width:100%; overflow-x:auto;'>

            <!--Card content-->
            <div class="card-body">

             <table class="table">
                            <!-- Table head -->
                            <thead class="blue-grey lighten-4">
                            <tr>
                                <th>S.No</th>
                                <th>Item Name</th>
                                <th>Category</th>
                                <th>Price</th>
                                <th>Discount Price</th>
                                <th></th>

                            </tr>
                            </thead>
                            <!-- Table head -->

                            <!-- Table body -->
                            <tbody>
                            {% for item in items %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{item.title}}</td>
                                <td>{{item.category.name}}</td>
                                <td>Rs. {{item.price}}</td>
                                <td>{% if item.discount_price %}
                                Rs. {{item.discount_price}}
                                {% endif %}
                                </td>
                                <td><a class='btn btn-sm btn-primary' href="{% url 'a:item-edit' pk=item.pk %}">Edit</a>
                                  <a class='btn btn-sm btn-danger' href="{% url 'a:item-delete' pk=item.pk %}">Delete</a>
                                
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                            <!-- Table body -->
                        </table>
                      <a class='btn btn-sm btn-warning' href="{% url 'a:item-create' %}">Add New</a>



            </div>

          </div>
          <!--/.Card-->

        </div>
      </div>
    </div>
  </main>
{% endblock content %}

admindashboard/templates/admin_item_update.html
{% extends 'admin_base.html' %}

{% load crispy_forms_tags %}

{% load widget_tweaks %}

{% block content %}

  <!--Main layout-->
  <main class="">
    <div class="container">

      <!--Grid row-->
      <div class="row wow fadeIn justify-content-center">

        <!--Grid column-->
        <div class="col-lg-12 col-md-12 col-sm-12 mb-4">

          <!--Card-->

            <!--Card content-->
            <div class='container'>
                <div class='row justify-content-center'>
                    <div class='col-lg-8 col-md-12 col-sm-12'>
                        <div class="card mt-4" style='width:100%; overflow-x:auto;'>
                            <h1 class='mt-4 ml-4'>Edit Item</h1>
                            <form class='card-body' method="POST" enctype="multipart/form-data">
                                {%csrf_token%}
                                
                                {{form|crispy}}
                                
                                <button class='btn btn-primary btn-lg btn-block waves-effect waves-light' type="submit">Save</button>
                            </form>
                        </div>

                    </div>


                </div>
            </div>
           


          <!--/.Card-->

        </div>
      </div>
    </div>
  </main>
{% endblock content %}

admindashboard/templates/admin_orders.html
{% extends 'admin_base.html' %}



{% block content %}

  <!--Main layout-->
  <main class="">
    <div class="container">

      <!--Grid row-->
      <div class="row wow fadeIn justify-content-center">

        <!--Grid column-->
        <div class="col-lg-12 col-md-12 col-sm-12 mb-4">

          <!--Card-->
          <div class="card" style='width:100%; overflow-x:auto;'>

            <!--Card content-->
            <div class="card-body">

              <!-- Table  -->
              <table class="table">
                <!-- Table head -->
                <thead class="blue-grey lighten-4">
                  <tr>
                    <th>Date</th>
                    <th>Order Id</th>
                    <th>Customer</th>
                    <th>Total</th>
                    <th>Status</th>
                    <th>TXN Id</th>
                    <th></th>
                  </tr>
                </thead>
                <!-- Table head -->

                <!-- Table body -->
                <tbody>
                  {% for order in orders %}

                  <tr>
                    <th>{{order.timestamp}}</th>
                    <th scope="row">{{order.order_id}}</th>
                   
                    <td>{{order.customer}}</td>
                    <td>Rs. {{order.total}}</td>
                    <td>
                        {% if order.is_paid %}
                            <span class="badge badge-success">Payment Success</span>
                        {% else %}
                            <span class="badge badge-warning">Payment Failed</span>
                        {% endif %}
                    </td>
                    
                    <td>{{order.transaction_id}}</td>
                    <td><a class='btn btn-sm btn-primary' href="{% url 'a:orders-detail' pk=order.pk %}">View</a>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
                <!-- Table body -->
              </table>
              <!-- Table  -->

            </div>

          </div>
          <!--/.Card-->

        </div>
      </div>
    </div>
  </main>
{% endblock content %}

admindashboard/templates/admin_orders_detail.html
{% extends 'admin_base.html' %}
{% block content %}


  <!--Main layout-->
  <main class="">
    <div class="container">

      <!--Grid row-->
      <div class="row wow fadeIn justify-content-center">

        <!--Grid column-->
        <div class="col-lg-12 col-md-12 col-sm-12 mb-4">
                 <!--Card-->
          <div class="card" style='width:100%; overflow-x:auto;'>

            <!--Card content-->
            <div class="card-body">

              <!-- Table  -->
              <table class="table">
                 <thead class="blue-grey lighten-4">
                  <tr>
                    <th colspan='2'>Order Details</th>

                  </tr>
                </thead>

                <!-- Table body -->
                <tbody>
                  <tr>
                    <th scope="row">Order Id</th>
                    <td>{{order.order_id}}</td>
                  </tr>
                  <tr>
                    <th scope="row">Customer</th>
                    <td>{{order.customer}}</td>
                  </tr>
                                    
                  <tr>
                    <th scope="row">Total Amount</th>
                    <td>Rs. {{order.total}}</td>
                  </tr>
                  <tr>
                    <th scope="row">Ordered Time</th>
                    <td>{{order.timestamp}}</td>
                  </tr>
                  
                  
                  <tr>
                    <th scope="row">Status</th>
                    <td>{% if order.is_paid %}
                            <span class="badge badge-success">Payment Success</span>
                        {% else %}
                            <span class="badge badge-warning">Payment Failed</span>
                        {% endif %}</td>
                  </tr>
                  <tr>
                    <th scope="row">TXN Id</th>
                    <td>{{order.transaction_id}}</td>
                  </tr>
                  <tr>
                    <th colspan='2'>Items</th>
                  </tr>
                  <tr>
                    <td colspan='2'>
                      <table class="table">
                        <thead class="lighten-4">
                          <tr>
                            <th scope='row'>#</th>
                            <th>Item</th>
                            <th>Size</th>
                            
                            <th>Quantity</th>
                            <th>Price Total</th>
                          </tr>
                        </thead>

                        <!-- Table body -->
                        <tbody>
                          {% for orderitem in order.orderitem_set.all %}
                          <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            
                            <td>{{orderitem.item_name}}</td>
                            <td>{{orderitem.size}}</td>
                            
                            <td>{{orderitem.quantity}}</td>
                            <td>{{orderitem.price_total}}</td>
                          </tr>
                          {% endfor %}

                        </tbody>
                        <!-- Table body -->
                      </table>
                    </td>
                  </tr>
                  <tr>
                    <th colspan='2'>Shipping Details</th>
                  </tr>
                  <tr>
                    <td>First Name</td>
                    <td>{{order.shipping_details.first_name}}</td>
                  </tr>
                  <tr>
                    <td>Last Name</td>
                    <td>{{order.shipping_details.last_name}}</td>
                  </tr>
                  <tr>
                    <td>Email</td>
                    <td>{{order.shipping_details.email}}</td>
                  </tr>
                  <tr>
                    <td>Address 1</td>
                    <td>{{order.shipping_details.address1}}</td>
                  </tr>
                  <tr>
                    <td>Address 2</td>
                    <td>{{order.shipping_details.address2}}</td>
                  </tr>
                  <tr>
                    <td>Mobile Number</td>
                    <td>{{order.shipping_details.phone}}</td>
                  </tr>
                  <tr>
                    <td>City</td>
                    <td>{{order.shipping_details.city}}</td>
                  </tr>
                  <tr>
                    <td>State</td>
                    <td>{{order.shipping_details.state}}</td>
                  </tr>
                  <tr>
                    <td>Zipcode</td>
                    <td>{{order.shipping_details.zipcode}}</td>
                  </tr>

                </tbody>
                <!-- Table body -->
              </table>
            </div>

          </div>
          <!--/.Card-->
        </div>
      </div>
    </div>
  </main>

{% endblock content %}